
version: "3.2"

services:
    timescreemer:
        image: php:7.1.11-fpm-alpine3.4
        volumes:
            - .:/source
        expose:
            - "9000"

    httpserver:
        image: nginx:alpine
        volumes:
            - ./docker/httpserver/nginx/conf:/etc/nginx/conf.d
            - ./docker/httpserver/nginx/logs:/var/log/nginx
            - .:/source
        ports:
            - "33080:80"
        expose:
            - "80"
            - "443"
